# hello-world-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world-gitops
spec:
  selector:
    app: hello-world-gitops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80